/**
 * Help & Support article catalog.
 * Metadata for Matching Articles / Popular lists; HTML lives under public/help-articles/.
 * Counts are derived from ARTICLES — do not hardcode category counts elsewhere.
 */

export interface HelpArticle {
  id: string;
  title: string;
  category: string;
  excerpt: string;
  /** Public URL path to the article HTML (served from public/help-articles/). */
  htmlPath: string;
  popular?: boolean;
}

export interface HelpCategory {
  id: string;
  label: string;
  description: string;
  count: number;
}

export const ARTICLES: HelpArticle[] = [
  { id: '01-getting-started-with-mynt-complete-setup-guide', title: 'Getting Started with Mynt: The Complete Setup Guide', category: 'getting-started', excerpt: 'Five steps take you from a new account to a dashboard with your own numbers in it. Each step has its own guide.', htmlPath: '/help-articles/getting-started/01-getting-started-with-mynt-complete-setup-guide.html', popular: true },
  { id: '02-how-to-create-your-mynt-account-and-sign-in', title: 'How to Create Your Mynt Account and Sign In', category: 'getting-started', excerpt: 'Two ways in: an email address and password, or Continue with Google. One of them only works if an account already exists.', htmlPath: '/help-articles/getting-started/02-how-to-create-your-mynt-account-and-sign-in.html' },
  { id: '03-how-to-complete-your-business-profile', title: 'How to Complete Your Business Profile', category: 'getting-started', excerpt: 'Your profile is what appears on every invoice Mynt raises. Get it right before your first purchase — an issued invoice cannot be changed afterwards.', htmlPath: '/help-articles/getting-started/03-how-to-complete-your-business-profile.html' },
  { id: '04-how-to-add-your-first-brand-and-outlet', title: 'How to Add Your First Brand and Outlet', category: 'getting-started', excerpt: 'Outlets are your physical locations. Brands and groups are the two ways to organise them — useful the moment you have more than one.', htmlPath: '/help-articles/getting-started/04-how-to-add-your-first-brand-and-outlet.html' },
  { id: '05-how-to-connect-your-data-sources-to-mynt', title: 'How to Connect Your Data Sources to Mynt', category: 'getting-started', excerpt: 'Mynt has one data source: the payout emails the platforms send you. Connecting the right mailbox is the step everything else waits on.', htmlPath: '/help-articles/getting-started/05-how-to-connect-your-data-sources-to-mynt.html' },
  { id: '06-understanding-mynt-navigation-date-filters-platform-filters-views', title: 'Finding Your Way Around Mynt: Navigation, Filters and Views', category: 'getting-started', excerpt: 'Mynt is one sidebar and one filter panel. Learn those two and every page makes sense.', htmlPath: '/help-articles/getting-started/06-understanding-mynt-navigation-date-filters-platform-filters-views.html' },
  { id: '01-connect-gmail-account', title: 'How to Connect Your Gmail Account to Mynt', category: 'email', excerpt: 'Mynt builds your dashboards from the payout emails Zomato and Swiggy send you. Connecting the mailbox those emails arrive in is the one step everything else depends on.', htmlPath: '/help-articles/email-integration/01-connect-gmail-account.html', popular: true },
  { id: '02-gmail-permissions', title: 'What Gmail Permissions Does Mynt Require?', category: 'email', excerpt: 'Mynt asks Google for read-only access to your Gmail. That is the whole ask, and it is the minimum that makes the product work.', htmlPath: '/help-articles/email-integration/02-gmail-permissions.html' },
  { id: '03-how-mynt-uses-emails', title: 'How Mynt Uses Your Emails to Build Your Dashboards', category: 'email', excerpt: 'Every figure in Mynt traces back to an email a platform sent you. Knowing that chain explains most of what people find surprising about the numbers.', htmlPath: '/help-articles/email-integration/03-how-mynt-uses-emails.html' },
  { id: '04-check-email-sync-status', title: 'How to Check Your Email Sync Status', category: 'email', excerpt: 'Two places tell you whether email is flowing: how fresh your data is, and whether the fetch stage is healthy. Check both before assuming something is broken.', htmlPath: '/help-articles/email-integration/04-check-email-sync-status.html' },
  { id: '05-how-often-sync', title: 'How Often Does Mynt Sync New Email Data?', category: 'email', excerpt: 'Mynt checks continuously, but it can only find what the platforms have sent. That distinction explains almost every "why is it not updated yet" question.', htmlPath: '/help-articles/email-integration/05-how-often-sync.html' },
  { id: '06-how-to-reconnect-gmail-when-connection-expires', title: 'How to Reconnect Gmail When the Connection Expires', category: 'email', excerpt: 'Google access can lapse — a password change, a revoked token, a security review. Reconnecting takes under a minute and no data is lost.', htmlPath: '/help-articles/email-integration/06-how-to-reconnect-gmail-when-connection-expires.html' },
  { id: '07-gmail-connected-but-data-missing-troubleshooting', title: 'Gmail Is Connected but My Data Is Missing', category: 'email', excerpt: 'The badge is green and the dashboard is still empty. Work through these four checks in order — the cause is almost always one of them.', htmlPath: '/help-articles/email-integration/07-gmail-connected-but-data-missing-troubleshooting.html' },
  { id: '08-how-to-disconnect-or-change-gmail-account', title: 'How to Disconnect or Change the Gmail Account Connected to Mynt', category: 'email', excerpt: 'There is no self-serve disconnect button in Mynt today. Here is what you can do yourself, and what needs support.', htmlPath: '/help-articles/email-integration/08-how-to-disconnect-or-change-gmail-account.html' },
  { id: '01-what-is-outlet-mapping-and-why-required', title: 'What Is Outlet Mapping and Why Is It Required?', category: 'outlets', excerpt: 'Zomato and Swiggy each give your restaurant their own ID number. Outlet mapping tells Mynt which of those IDs belong to which of your outlets, so your payout emails land against the right shop.', htmlPath: '/help-articles/outlet-mapping/01-what-is-outlet-mapping-and-why-required.html', popular: true },
  { id: '02-how-to-map-zomato-swiggy-platform-outlets', title: 'How to Map Zomato and Swiggy Outlets', category: 'outlets', excerpt: 'Linking a Zomato or Swiggy restaurant ID to one of your outlets makes payouts for that ID count against the right shop.', htmlPath: '/help-articles/outlet-mapping/02-how-to-map-zomato-swiggy-platform-outlets.html' },
  { id: '03-how-to-edit-existing-outlet-mapping', title: 'How to Edit an Existing Outlet Mapping', category: 'outlets', excerpt: 'Renamed a shop, or linked the wrong restaurant ID? Everything in Platform Mapping can be changed from the same Edit button.', htmlPath: '/help-articles/outlet-mapping/03-how-to-edit-existing-outlet-mapping.html' },
  { id: '04-how-outlet-mapping-works-multiple-outlets-chains-groups', title: 'How Outlet Mapping Works for Multiple Outlets, Brands and Groups', category: 'outlets', excerpt: 'Running more than one shop, or more than one brand out of them? Mynt organises outlets in three layers. Only the first affects your data; the other two make filtering easier.', htmlPath: '/help-articles/outlet-mapping/04-how-outlet-mapping-works-multiple-outlets-chains-groups.html' },
  { id: '05-how-to-fix-incorrect-duplicate-unmapped-outlets', title: 'How to Fix Incorrect, Duplicate or Unmapped Outlets', category: 'outlets', excerpt: 'Missing numbers on your dashboard usually trace back to mapping. Five things commonly go wrong, and each has a fix.', htmlPath: '/help-articles/outlet-mapping/05-how-to-fix-incorrect-duplicate-unmapped-outlets.html' },
  { id: '01-understanding-the-mynt-dashboard', title: 'Understanding the Mynt Dashboard', category: 'dashboard', excerpt: 'The dashboard answers one question: how did the business do over a chosen period? Everything on it is either the period you picked, a number for that period, or a comparison against the period before.', htmlPath: '/help-articles/dashboard-metrics/01-understanding-the-mynt-dashboard.html' },
  { id: '02-how-to-use-filters-date-platform-restaurant-chain-group', title: 'How to Use the Filters: Date, Platform, Outlet, Brand and Group', category: 'dashboard', excerpt: 'The filter panel decides what every number on the page counts. Four controls, and they apply everywhere.', htmlPath: '/help-articles/dashboard-metrics/02-how-to-use-filters-date-platform-restaurant-chain-group.html' },
  { id: '03-understanding-sales-gross-order-value', title: 'Understanding Sales and Gross Order Value', category: 'dashboard', excerpt: 'Gross Order Value is the top line: what customers were billed, before the platforms take anything out. It is not what you get paid.', htmlPath: '/help-articles/dashboard-metrics/03-understanding-sales-gross-order-value.html' },
  { id: '04-understanding-orders-and-average-order-value', title: 'Understanding Orders and Average Order Value', category: 'dashboard', excerpt: 'Two cards that only make sense together: how many orders came in, and how much each was worth.', htmlPath: '/help-articles/dashboard-metrics/04-understanding-orders-and-average-order-value.html' },
  { id: '05-understanding-discounts-and-discount-percent', title: 'Understanding Discounts and Discount Percent', category: 'dashboard', excerpt: 'Discounts are the easiest cost to underestimate, because they never appear as a bill. Mynt reports them as a value and as a share of sales.', htmlPath: '/help-articles/dashboard-metrics/05-understanding-discounts-and-discount-percent.html' },
  { id: '06-understanding-advertising-spend-and-ad-performance', title: 'Understanding Advertising Spend and Ad Performance', category: 'dashboard', excerpt: 'What you spent on platform advertising, and what it bought. Unlike discounts, this one does arrive as a bill — which makes it easier to judge.', htmlPath: '/help-articles/dashboard-metrics/06-understanding-advertising-spend-and-ad-performance.html' },
  { id: '07-understanding-platform-charges-commissions-payouts', title: 'Understanding Platform Charges, Commissions and Payouts', category: 'dashboard', excerpt: 'The gap between what customers paid and what reaches your bank. This is where it goes.', htmlPath: '/help-articles/dashboard-metrics/07-understanding-platform-charges-commissions-payouts.html', popular: true },
  { id: '08-understanding-net-margin-and-profitability', title: 'Understanding Net Margin and Profitability', category: 'dashboard', excerpt: 'Net Margin is the one number that ties the rest together: what share of what customers paid you actually keep.', htmlPath: '/help-articles/dashboard-metrics/08-understanding-net-margin-and-profitability.html' },
  { id: '09-how-to-read-growth-trends-comparisons-ai-insights', title: 'How to Read Growth Trends, Comparisons and AI Insights', category: 'dashboard', excerpt: 'Below the headline cards sit the three tools for working out why a number moved: the platform split, the trend line, and the insights panel.', htmlPath: '/help-articles/dashboard-metrics/09-how-to-read-growth-trends-comparisons-ai-insights.html' },
  { id: '01-what-reports-are-available', title: 'What Reports Are Available in Mynt', category: 'reports', excerpt: 'One builder covers every report. You choose what it contains, which outlets and period it covers, and how it reaches you.', htmlPath: '/help-articles/reports/01-what-reports-are-available.html' },
  { id: '02-how-to-generate-and-download-report', title: 'How to Generate and Download a Report', category: 'reports', excerpt: 'Fill in four fields, check the token cost, and generate. The cost is always shown before you commit.', htmlPath: '/help-articles/reports/02-how-to-generate-and-download-report.html' },
  { id: '03-schedule-automatic-reports', title: 'How to Schedule Automatic Reports', category: 'reports', excerpt: 'The same builder can deliver a report on a recurring basis instead of once. Set it up in the same place.', htmlPath: '/help-articles/reports/03-schedule-automatic-reports.html', popular: true },
  { id: '04-how-to-manage-report-schedules', title: 'How to Manage Your Report Schedules', category: 'reports', excerpt: 'Every recurring report you have set up is listed in one place, with filters for finding the one you want.', htmlPath: '/help-articles/reports/04-how-to-manage-report-schedules.html' },
  { id: '01-what-are-mynt-tokens', title: 'What Are Mynt Tokens?', category: 'tokens', excerpt: 'Tokens are Mynt’s pay-as-you-go currency for the features that cost something to run. They are separate from your outlet licences.', htmlPath: '/help-articles/tokens/01-what-are-mynt-tokens.html', popular: true },
  { id: '02-which-mynt-features-consume-tokens', title: 'Which Mynt Features Consume Tokens?', category: 'tokens', excerpt: 'Three things spend tokens: AI Assistant queries, report runs and notifications. Reports are usually the largest by far.', htmlPath: '/help-articles/tokens/02-which-mynt-features-consume-tokens.html' },
  { id: '03-how-to-check-token-usage-balance-get-more', title: 'How to Check Your Token Balance and Get More', category: 'tokens', excerpt: 'Your balance is on the Billing page, and so are the packs. Both are two clicks from anywhere in Mynt.', htmlPath: '/help-articles/tokens/03-how-to-check-token-usage-balance-get-more.html' },
  { id: '01-understanding-mynt-pricing-annual-outlet-licences', title: 'Understanding Mynt Pricing and Annual Outlet Licences', category: 'billing', excerpt: 'Mynt is priced per outlet, per year. One licence covers one outlet for twelve months. Here is exactly what that buys and what it costs.', htmlPath: '/help-articles/billing/01-understanding-mynt-pricing-annual-outlet-licences.html' },
  { id: '02-how-to-purchase-mynt-licences', title: 'How to Purchase Mynt Licences', category: 'billing', excerpt: 'Buying licences takes about a minute. Everything is priced on screen before you pay, and nothing is charged until you confirm.', htmlPath: '/help-articles/billing/02-how-to-purchase-mynt-licences.html' },
  { id: '03-how-to-add-more-outlet-licences', title: 'How to Add More Outlet Licences', category: 'billing', excerpt: 'Opened a new location? Add a licence for it. The process is the same as your first purchase, and your existing licences are untouched.', htmlPath: '/help-articles/billing/03-how-to-add-more-outlet-licences.html' },
  { id: '04-understanding-licence-dates-expiry-renewals', title: 'Understanding Licence Dates, Expiry and Renewals', category: 'billing', excerpt: 'Every licence carries its own dates. The licence table shows what each one covers, how long it has left, and what happens when it runs out.', htmlPath: '/help-articles/billing/04-understanding-licence-dates-expiry-renewals.html' },
  { id: '05-how-to-view-download-invoices', title: 'How to View and Download Invoices', category: 'billing', excerpt: 'Every payment on your account has an invoice you can open on screen or download as a PDF for your accountant.', htmlPath: '/help-articles/billing/05-how-to-view-download-invoices.html' },
  { id: '06-how-payments-gst-billing-details-work', title: 'How Payments, GST and Billing Details Work', category: 'billing', excerpt: 'What Mynt accepts, how GST is applied, and which details end up printed on your invoice.', htmlPath: '/help-articles/billing/06-how-payments-gst-billing-details-work.html' },
  { id: '07-troubleshooting-failed-payments-renewals', title: 'Troubleshooting Failed Payments and Renewals', category: 'billing', excerpt: 'A payment did not go through, or a renewal is due. Here is how to tell which, and what to do about it.', htmlPath: '/help-articles/billing/07-troubleshooting-failed-payments-renewals.html' },
  { id: '01-why-todays-recent-data-not-showing', title: 'Why Today\'s or Recent Data Is Not Showing Yet', category: 'data', excerpt: 'You opened Mynt expecting yesterday’s sales and the dashboard looks a few days behind. Most of the time this is normal. Here is why it happens and what to check.', htmlPath: '/help-articles/data-issues/01-why-todays-recent-data-not-showing.html' },
  { id: '02-what-to-do-when-data-missing-certain-dates', title: 'What to Do When Data Is Missing for Certain Dates', category: 'data', excerpt: 'Most weeks look right, but one specific stretch is blank. Four things cause that, in the order worth checking them.', htmlPath: '/help-articles/data-issues/02-what-to-do-when-data-missing-certain-dates.html', popular: true },
  { id: '03-what-to-do-when-dashboard-numbers-incorrect', title: 'What to Do When Dashboard Numbers Look Incorrect', category: 'data', excerpt: 'A figure looks too high, too low, or does not match what the platform app says. Nine times out of ten the number is right and the two of you are counting different things.', htmlPath: '/help-articles/data-issues/03-what-to-do-when-dashboard-numbers-incorrect.html', popular: true },
  { id: '04-why-zomato-swiggy-data-missing-incomplete', title: 'Why Zomato or Swiggy Data Is Missing or Incomplete', category: 'data', excerpt: 'Zomato is there and Swiggy is blank, or the other way round. When only one platform is affected, the cause is nearly always that platform’s ID or that platform’s emails.', htmlPath: '/help-articles/data-issues/04-why-zomato-swiggy-data-missing-incomplete.html' },
  { id: '05-how-incorrect-outlet-mapping-affects-data', title: 'How Incorrect Outlet Mapping Affects Your Data', category: 'data', excerpt: 'Outlet mapping decides which orders belong to which shop. Get it wrong and the numbers are not slightly off — they are attributed to the wrong outlet, or dropped entirely.', htmlPath: '/help-articles/data-issues/05-how-incorrect-outlet-mapping-affects-data.html' },
  { id: '06-how-to-raise-data-issue-support-ticket', title: 'How to Raise a Data Issue Support Ticket', category: 'data', excerpt: 'When the checks have not solved it, raise a ticket from inside Mynt. A ticket with the right details is usually answered in one reply instead of three.', htmlPath: '/help-articles/data-issues/06-how-to-raise-data-issue-support-ticket.html' },
  { id: '01-how-sign-in-account-access-work', title: 'How Sign-In and Account Access Work in Mynt', category: 'security', excerpt: 'Mynt signs you in with an email and password, or with Google. Your session stays open on that browser until you sign out or it expires.', htmlPath: '/help-articles/security/01-how-sign-in-account-access-work.html' },
  { id: '02-understanding-google-gmail-permissions', title: 'Understanding Google and Gmail Permissions', category: 'security', excerpt: 'Connecting Gmail is separate from signing in to Mynt. Google shows its own screen when you connect, and what it grants Mynt is read-only access to your inbox.', htmlPath: '/help-articles/security/02-understanding-google-gmail-permissions.html' },
  { id: '03-how-mynt-protects-business-data', title: 'How Mynt Protects Your Business Data', category: 'security', excerpt: 'Your payout data is sensitive: sales, commissions, bank settlements. Passwords are hashed, traffic runs over HTTPS, card details are handled by a PCI-compliant payment company rather than stored by Mynt, and Gmail', htmlPath: '/help-articles/security/03-how-mynt-protects-business-data.html' },
  { id: '04-how-to-disconnect-sign-out-remove-access', title: 'How to Disconnect Integrations, Sign Out or Remove Account Access', category: 'security', excerpt: 'Signing out of Mynt, ending every session on every device, and changing which Gmail is connected are three different actions with three different effects.', htmlPath: '/help-articles/security/04-how-to-disconnect-sign-out-remove-access.html' },
];

const CATEGORY_DEFS: Omit<HelpCategory, 'count'>[] = [
  { id: 'getting-started', label: 'Getting Started', description: 'Setup, email connection' },
  { id: 'email', label: 'Email Integration', description: 'Gmail connection, sync issues' },
  { id: 'outlets', label: 'Outlet Mapping', description: 'Mapping help' },
  { id: 'dashboard', label: 'Dashboard & Metrics', description: 'Understanding metrics' },
  { id: 'reports', label: 'Reports', description: 'Scheduling reports' },
  { id: 'tokens', label: 'Tokens', description: 'Token usage' },
  { id: 'billing', label: 'Billing', description: 'Plans, invoices' },
  { id: 'data', label: 'Data Issues', description: 'Missing data' },
  { id: 'security', label: 'Security', description: 'Login, password' },
];

export const CATEGORIES: HelpCategory[] = CATEGORY_DEFS.map((c) => ({
  ...c,
  count: ARTICLES.filter((a) => a.category === c.id).length,
}));

export function getPopularArticles(): HelpArticle[] {
  return ARTICLES.filter((a) => a.popular);
}

